services:
  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro'

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    privileged: true  # Add this line
    ports:
      - "9115:9115"  # Add this line
    command:
      - "--config.file=/config/blackbox.yml"
    volumes:
      - ./blackbox.yml:/config/blackbox.yml

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    ports:
      - "5000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
